import { UserProfile } from '../types';

export const MOCK_USER_PROFILES: UserProfile[] = [
  {
    id: 'user-1',
    name: '의대지망생_A',
    points: 2500,
    hasContributed: true,
    inventory: [],
    unlockedLogIds: [],
    likedLogIds: [],
    dislikedLogIds: [],
    school: '서울고등학교',
    grade: '고3',
    targetUniversity: '서울대 의대',
    currentGrades: {
      korean: '2등급',
      math: '1등급',
      english: '1등급',
      science1: '1등급',
      science2: '2등급'
    },
    studyHoursPerDay: 12,
    weakSubjects: ['국어'],
    studyLocation: '독서실',
    profileCompleted: true
  },
  {
    id: 'user-2',
    name: 'N수생의외침',
    points: 3200,
    hasContributed: true,
    inventory: [],
    unlockedLogIds: [],
    likedLogIds: [],
    dislikedLogIds: [],
    school: 'N수학원',
    grade: 'N수생',
    targetUniversity: '연세대 공대',
    currentGrades: {
      korean: '3등급',
      math: '2등급',
      english: '2등급',
      science1: '2등급',
      science2: '3등급'
    },
    studyHoursPerDay: 10,
    weakSubjects: ['국어', '화학'],
    studyLocation: '학원',
    profileCompleted: true
  },
  {
    id: 'user-3',
    name: '공대생김철수',
    points: 1800,
    hasContributed: true,
    inventory: [],
    unlockedLogIds: [],
    likedLogIds: [],
    dislikedLogIds: [],
    school: '부산과학고',
    grade: '고3',
    targetUniversity: 'KAIST',
    currentGrades: {
      korean: '4등급',
      math: '1등급',
      english: '2등급',
      science1: '1등급',
      science2: '1등급'
    },
    studyHoursPerDay: 11,
    weakSubjects: ['국어'],
    studyLocation: '집',
    profileCompleted: true
  },
  {
    id: 'user-4',
    name: '문과여신',
    points: 2100,
    hasContributed: true,
    inventory: [],
    unlockedLogIds: [],
    likedLogIds: [],
    dislikedLogIds: [],
    school: '이화여고',
    grade: '고3',
    targetUniversity: '서울대 인문대',
    currentGrades: {
      korean: '1등급',
      math: '3등급',
      english: '1등급',
      social: '2등급'
    },
    studyHoursPerDay: 9,
    weakSubjects: ['수학'],
    studyLocation: '도서관',
    profileCompleted: true
  },
  {
    id: 'user-5',
    name: '재수생박민수',
    points: 1500,
    hasContributed: true,
    inventory: [],
    unlockedLogIds: [],
    likedLogIds: [],
    dislikedLogIds: [],
    school: '대치학원',
    grade: 'N수생',
    targetUniversity: '고려대 경영대',
    currentGrades: {
      korean: '2등급',
      math: '3등급',
      english: '2등급',
      social: '2등급'
    },
    studyHoursPerDay: 8,
    weakSubjects: ['수학'],
    studyLocation: '집',
    profileCompleted: true
  },
  {
    id: 'user-6',
    name: '화학덕후',
    points: 2800,
    hasContributed: true,
    inventory: [],
    unlockedLogIds: [],
    likedLogIds: [],
    dislikedLogIds: [],
    school: '경기과학고',
    grade: '고3',
    targetUniversity: '서울대 화학과',
    currentGrades: {
      korean: '3등급',
      math: '1등급',
      english: '2등급',
      science1: '1등급',
      science2: '1등급'
    },
    studyHoursPerDay: 13,
    weakSubjects: ['국어'],
    studyLocation: '독서실',
    profileCompleted: true
  },
  {
    id: 'user-7',
    name: '국어킬러',
    points: 1900,
    hasContributed: true,
    inventory: [],
    unlockedLogIds: [],
    likedLogIds: [],
    dislikedLogIds: [],
    school: '강남고등학교',
    grade: '고2',
    targetUniversity: '서울대 국문과',
    currentGrades: {
      korean: '1등급',
      math: '4등급',
      english: '2등급',
      social: '1등급'
    },
    studyHoursPerDay: 7,
    weakSubjects: ['수학'],
    studyLocation: '도서관',
    profileCompleted: true
  },
  {
    id: 'user-8',
    name: '물리마스터',
    points: 3500,
    hasContributed: true,
    inventory: [],
    unlockedLogIds: [],
    likedLogIds: [],
    dislikedLogIds: [],
    school: '한성과학고',
    grade: '고3',
    targetUniversity: 'POSTECH 물리학과',
    currentGrades: {
      korean: '2등급',
      math: '1등급',
      english: '1등급',
      science1: '1등급',
      science2: '1등급'
    },
    studyHoursPerDay: 14,
    weakSubjects: [],
    studyLocation: '학교',
    profileCompleted: true
  },
  {
    id: 'user-9',
    name: '생명과학러버',
    points: 2200,
    hasContributed: true,
    inventory: [],
    unlockedLogIds: [],
    likedLogIds: [],
    dislikedLogIds: [],
    school: '대원외고',
    grade: '고3',
    targetUniversity: '연세대 의대',
    currentGrades: {
      korean: '2등급',
      math: '2등급',
      english: '1등급',
      science1: '1등급',
      science2: '2등급'
    },
    studyHoursPerDay: 11,
    weakSubjects: ['수학'],
    studyLocation: '독서실',
    profileCompleted: true
  },
  {
    id: 'user-10',
    name: '사탐고수',
    points: 1600,
    hasContributed: true,
    inventory: [],
    unlockedLogIds: [],
    likedLogIds: [],
    dislikedLogIds: [],
    school: '중동고등학교',
    grade: '고3',
    targetUniversity: '성균관대 사회과학대',
    currentGrades: {
      korean: '2등급',
      math: '4등급',
      english: '3등급',
      social: '1등급'
    },
    studyHoursPerDay: 8,
    weakSubjects: ['수학', '영어'],
    studyLocation: '집',
    profileCompleted: true
  },
  {
    id: 'user-11',
    name: '영어마스터',
    points: 2700,
    hasContributed: true,
    inventory: [],
    unlockedLogIds: [],
    likedLogIds: [],
    dislikedLogIds: [],
    school: '외대부고',
    grade: '고3',
    targetUniversity: '서울대 영문과',
    currentGrades: {
      korean: '2등급',
      math: '3등급',
      english: '1등급',
      social: '1등급'
    },
    studyHoursPerDay: 9,
    weakSubjects: ['수학'],
    studyLocation: '도서관',
    profileCompleted: true
  },
  {
    id: 'user-12',
    name: '수학천재꿈나무',
    points: 3100,
    hasContributed: true,
    inventory: [],
    unlockedLogIds: [],
    likedLogIds: [],
    dislikedLogIds: [],
    school: '서울과학고',
    grade: '고2',
    targetUniversity: 'KAIST 수학과',
    currentGrades: {
      korean: '3등급',
      math: '1등급',
      english: '2등급',
      science1: '1등급',
      science2: '2등급'
    },
    studyHoursPerDay: 12,
    weakSubjects: ['국어'],
    studyLocation: '학교',
    profileCompleted: true
  },
  {
    id: 'user-13',
    name: '지구과학탐험가',
    points: 1400,
    hasContributed: true,
    inventory: [],
    unlockedLogIds: [],
    likedLogIds: [],
    dislikedLogIds: [],
    school: '인천고등학교',
    grade: '고3',
    targetUniversity: '부산대 지구과학과',
    currentGrades: {
      korean: '4등급',
      math: '3등급',
      english: '3등급',
      science1: '2등급',
      science2: '2등급'
    },
    studyHoursPerDay: 6,
    weakSubjects: ['국어', '수학'],
    studyLocation: '집',
    profileCompleted: true
  },
  {
    id: 'user-14',
    name: '세계사여행자',
    points: 1800,
    hasContributed: true,
    inventory: [],
    unlockedLogIds: [],
    likedLogIds: [],
    dislikedLogIds: [],
    school: '동성고등학교',
    grade: '고3',
    targetUniversity: '한국외대 사학과',
    currentGrades: {
      korean: '2등급',
      math: '5등급',
      english: '2등급',
      social: '1등급'
    },
    studyHoursPerDay: 7,
    weakSubjects: ['수학'],
    studyLocation: '도서관',
    profileCompleted: true
  },
  {
    id: 'user-15',
    name: '경제학도',
    points: 2400,
    hasContributed: true,
    inventory: [],
    unlockedLogIds: [],
    likedLogIds: [],
    dislikedLogIds: [],
    school: '휘문고등학교',
    grade: '고3',
    targetUniversity: '서울대 경제학과',
    currentGrades: {
      korean: '2등급',
      math: '2등급',
      english: '1등급',
      social: '1등급'
    },
    studyHoursPerDay: 10,
    weakSubjects: ['수학'],
    studyLocation: '독서실',
    profileCompleted: true
  },
  {
    id: 'user-16',
    name: '정치외교관',
    points: 2000,
    hasContributed: true,
    inventory: [],
    unlockedLogIds: [],
    likedLogIds: [],
    dislikedLogIds: [],
    school: '배재고등학교',
    grade: 'N수생',
    targetUniversity: '연세대 정치외교학과',
    currentGrades: {
      korean: '1등급',
      math: '4등급',
      english: '1등급',
      social: '1등급'
    },
    studyHoursPerDay: 9,
    weakSubjects: ['수학'],
    studyLocation: '학원',
    profileCompleted: true
  },
  {
    id: 'user-17',
    name: '사회문화연구자',
    points: 1700,
    hasContributed: true,
    inventory: [],
    unlockedLogIds: [],
    likedLogIds: [],
    dislikedLogIds: [],
    school: '숙명여고',
    grade: '고3',
    targetUniversity: '이화여대 사회학과',
    currentGrades: {
      korean: '2등급',
      math: '4등급',
      english: '2등급',
      social: '2등급'
    },
    studyHoursPerDay: 8,
    weakSubjects: ['수학'],
    studyLocation: '집',
    profileCompleted: true
  },
  {
    id: 'user-18',
    name: '윤리학자',
    points: 1300,
    hasContributed: true,
    inventory: [],
    unlockedLogIds: [],
    likedLogIds: [],
    dislikedLogIds: [],
    school: '경복고등학교',
    grade: '고2',
    targetUniversity: '서울대 철학과',
    currentGrades: {
      korean: '1등급',
      math: '5등급',
      english: '3등급',
      social: '1등급'
    },
    studyHoursPerDay: 6,
    weakSubjects: ['수학', '영어'],
    studyLocation: '도서관',
    profileCompleted: true
  },
  {
    id: 'user-19',
    name: '철학도',
    points: 1900,
    hasContributed: true,
    inventory: [],
    unlockedLogIds: [],
    likedLogIds: [],
    dislikedLogIds: [],
    school: '보성고등학교',
    grade: '고3',
    targetUniversity: '고려대 철학과',
    currentGrades: {
      korean: '1등급',
      math: '4등급',
      english: '2등급',
      social: '1등급'
    },
    studyHoursPerDay: 7,
    weakSubjects: ['수학'],
    studyLocation: '집',
    profileCompleted: true
  },
  {
    id: 'user-20',
    name: '미래의의사',
    points: 4000,
    hasContributed: true,
    inventory: [],
    unlockedLogIds: [],
    likedLogIds: [],
    dislikedLogIds: [],
    school: '민족사관고',
    grade: '고3',
    targetUniversity: '서울대 의대',
    currentGrades: {
      korean: '1등급',
      math: '1등급',
      english: '1등급',
      science1: '1등급',
      science2: '1등급'
    },
    studyHoursPerDay: 15,
    weakSubjects: [],
    studyLocation: '독서실',
    profileCompleted: true
  }
];