import { FailureLog } from '../types';

export const MOCK_FAILURE_LOGS: FailureLog[] = [
  {
    id: 'mock-1',
    authorId: 'user-1',
    authorName: '의대지망생_A',
    title: '6월 학평 국어 시간부족 대참사',
    date: '2024-06-15',
    category: 'Mock Exam',
    score: '국어 4등급',
    tags: ['시간 조절 실패', '긴장/불안감'],
    description: '비문학 마지막 지문 하나를 통째로 날렸습니다. 처음에 너무 꼼꼼하게 읽으려다가 망했네요. 실전에서는 과감함이 필요하다는 걸 뼈저리게 느꼈습니다.',
    aiAdvice: '### 근본 원인 인사이트\n완벽주의적 독해가 오히려 전반적인 시간 관리를 무너뜨렸습니다.\n\n### 다른 수험생들과의 비교\n많은 상위권 학생들이 겪는 전형적인 "매몰 현상"입니다. 보통 이런 경우 한 지문에 15분 이상을 쓰다가 멘탈이 흔들려 뒷부분을 마킹도 못하는 경우가 많습니다. 합격생들은 이를 방지하기 위해 지문당 "데드라인"을 설정합니다.\n\n### 행동 강령\n1. 지문당 시간 한계선 설정\n2. 쉬운 문제부터 풀기\n3. 매일 아침 시간 재고 풀기',
    createdAt: Date.now() - 1000000,
    likes: 42,
    dislikes: 2,
    isPublic: true,
    rewardClaimed: true
  },
  {
    id: 'mock-2',
    authorId: 'user-2',
    authorName: 'N수생의외침',
    title: '밤샘 공부 후 다음날 리듬 붕괴',
    date: '2024-08-01',
    category: 'Daily Plan',
    tags: ['수면 부족', '번아웃'],
    description: '새벽 4시까지 공부하고 다음날 11시에 일어났더니 하루 전체 계획이 꼬여버렸습니다. 결국 어제 한 거보다 오늘 못한 게 더 많네요.',
    aiAdvice: '### 근본 원인 인사이트\n단기적 몰입이 장기적 시스템을 파괴한 전형적인 오버페이스 사례입니다.\n\n### 다른 수험생들과의 비교\n시험 직전 불안감에 휩싸인 수험생의 60% 이상이 밤샘을 시도하지만, 결과적으로 다음날 학습 효율은 평소의 30% 이하로 떨어집니다. 성공한 N수생들은 밤샘 대신 일찍 자고 새벽에 일어나는 방식을 선호합니다.\n\n### 행동 강령\n1. 최소 수면 6시간 사수\n2. 취침 1시간 전 스마트폰 차단\n3. 루틴 붕괴 시 즉각 휴식 후 정비',
    createdAt: Date.now() - 500000,
    likes: 85,
    dislikes: 5,
    isPublic: true,
    rewardClaimed: true
  },
  {
    id: 'mock-3',
    authorId: 'user-3',
    authorName: '공대생김철수',
    title: '수학 킬러문제에 40분 투자하고 망함',
    date: '2024-09-12',
    category: 'Mock Exam',
    score: '수학 3등급',
    tags: ['시간 조절 실패', '과도한 고민(함정)'],
    description: '30번 문제가 너무 어려워서 계속 붙잡고 있었는데 결국 못 풀고 뒤에 쉬운 문제들도 다 못했어요. 전략적 포기가 필요했는데...',
    aiAdvice: '### 근본 원인 인사이트\n"모든 문제를 풀어야 한다"는 강박이 전체적인 점수 최적화를 방해했습니다.\n\n### 다른 수험생들과의 비교\n상위권 학생일수록 킬러문제에 매몰되는 경향이 강합니다. 하지만 1등급 학생들은 "15분 룰"을 적용해 일정 시간 후 과감히 넘어갑니다.\n\n### 행동 강령\n1. 문제당 최대 투자 시간 미리 설정\n2. 뒤에서부터 풀어보기\n3. 부분점수 전략 활용',
    createdAt: Date.now() - 400000,
    likes: 67,
    dislikes: 3,
    isPublic: true,
    rewardClaimed: true
  },
  {
    id: 'mock-4',
    authorId: 'user-4',
    authorName: '문과여신',
    title: '영어 듣기에서 멘탈 나가서 뒤 다 망침',
    date: '2024-07-20',
    category: 'Mock Exam',
    score: '영어 2등급',
    tags: ['긴장/불안감', '과도한 고민(함정)'],
    description: '듣기 8번을 못 들었는데 그게 너무 신경쓰여서 뒤에 독해도 집중이 안됐어요. 한 문제 때문에 전체가 무너졌네요.',
    aiAdvice: '### 근본 원인 인사이트\n하나의 실수가 연쇄적으로 멘탈을 흔드는 "도미노 효과"가 발생했습니다.\n\n### 다른 수험생들과의 비교\n많은 수험생이 듣기에서 실수하면 독해까지 영향받습니다. 고득점자들은 "구간별 리셋" 능력이 뛰어납니다.\n\n### 행동 강령\n1. 각 영역별 독립적 사고\n2. 실수 후 3초 심호흡 루틴\n3. "이미 지나간 것" 인정하기',
    createdAt: Date.now() - 350000,
    likes: 54,
    dislikes: 1,
    isPublic: true,
    rewardClaimed: true
  },
  {
    id: 'mock-5',
    authorId: 'user-5',
    authorName: '재수생박민수',
    title: '스마트폰 유튜브에 빠져서 하루 날림',
    date: '2024-10-05',
    category: 'Daily Plan',
    tags: ['스마트폰/집중력', '무기력/번아웃'],
    description: '공부하려고 책상에 앉았는데 "잠깐만" 하고 폰을 봤다가 5시간이 지나있었어요. 유튜브 알고리즘이 너무 무서워요.',
    aiAdvice: '### 근본 원인 인사이트\n도파민 중독 상태에서 의지력만으로는 통제가 불가능합니다.\n\n### 다른 수험생들과의 비교\n수험생의 80% 이상이 스마트폰 때문에 공부 계획이 틀어진 경험이 있습니다. 성공한 학생들은 물리적 차단을 선택합니다.\n\n### 행동 강령\n1. 공부 시간에는 폰을 다른 방에 두기\n2. 앱 사용 시간 제한 설정\n3. 공부 후 보상으로 폰 사용하기',
    createdAt: Date.now() - 300000,
    likes: 123,
    dislikes: 8,
    isPublic: true,
    rewardClaimed: true
  },
  {
    id: 'mock-6',
    authorId: 'user-6',
    authorName: '화학덕후',
    title: '화학 실험 문제에서 단위 실수로 틀림',
    date: '2024-09-28',
    category: 'Mock Exam',
    score: '화학 2등급',
    tags: ['실수(계산/마킹)', '과도한 고민(함정)'],
    description: 'mol을 g으로 바꾸는 과정에서 분자량을 잘못 곱해서 답이 완전히 틀렸어요. 개념은 다 아는데 이런 실수가 너무 아까워요.',
    aiAdvice: '### 근본 원인 인사이트\n개념 이해와 실행 정확성 사이의 갭이 존재합니다.\n\n### 다른 수험생들과의 비교\n이과생들의 가장 흔한 실수 유형입니다. 상위권일수록 단위 실수에 민감하게 반응합니다.\n\n### 행동 강령\n1. 단위 변환 시 반드시 검산하기\n2. 문제에서 요구하는 단위 먼저 확인\n3. 계산 과정을 단계별로 적기',
    createdAt: Date.now() - 250000,
    likes: 34,
    dislikes: 2,
    isPublic: true,
    rewardClaimed: true
  },
  {
    id: 'mock-7',
    authorId: 'user-7',
    authorName: '국어킬러',
    title: '문학 작품 해석을 완전 반대로 이해함',
    date: '2024-08-15',
    category: 'Mock Exam',
    score: '국어 3등급',
    tags: ['개념 부족', '과도한 고민(함정)'],
    description: '화자의 정서를 긍정적으로 봤는데 실제로는 부정적이었어요. 문맥을 잘못 파악한 것 같아요.',
    aiAdvice: '### 근본 원인 인사이트\n문학적 맥락 파악 능력이 부족한 상태입니다.\n\n### 다른 수험생들과의 비교\n문학 해석 오류는 매우 흔합니다. 고득점자들은 키워드 중심으로 객관적 근거를 찾습니다.\n\n### 행동 강령\n1. 화자의 상황과 배경 먼저 파악\n2. 감정 표현 어휘에 주목하기\n3. 주관적 해석보다 텍스트 근거 우선',
    createdAt: Date.now() - 200000,
    likes: 28,
    dislikes: 4,
    isPublic: true,
    rewardClaimed: true
  },
  {
    id: 'mock-8',
    authorId: 'user-8',
    authorName: '물리마스터',
    title: '물리 역학 문제에서 방향 설정 실수',
    date: '2024-10-12',
    category: 'Mock Exam',
    score: '물리 1등급',
    tags: ['실수(계산/마킹)', '시간 조절 실패'],
    description: '힘의 방향을 반대로 설정해서 답이 음수로 나왔는데 절댓값만 쓰고 넘어갔어요. 기본기 실수가 제일 아까워요.',
    aiAdvice: '### 근본 원인 인사이트\n기본 개념 적용에서의 부주의가 원인입니다.\n\n### 다른 수험생들과의 비교\n물리 고득점자들도 방향 설정에서 실수하는 경우가 많습니다. 체계적인 좌표계 설정이 중요합니다.\n\n### 행동 강령\n1. 문제 시작 전 좌표계 명확히 설정\n2. 벡터 방향 표시를 습관화\n3. 답의 물리적 의미 검토하기',
    createdAt: Date.now() - 150000,
    likes: 19,
    dislikes: 1,
    isPublic: true,
    rewardClaimed: true
  },
  {
    id: 'mock-9',
    authorId: 'user-9',
    authorName: '생명과학러버',
    title: '생명과학 그래프 해석에서 축 헷갈림',
    date: '2024-09-03',
    category: 'Mock Exam',
    score: '생명과학 2등급',
    tags: ['실수(계산/마킹)', '긴장/불안감'],
    description: 'x축과 y축을 바꿔서 읽었어요. 그래프 문제는 항상 조심해야 하는데 시험장에서 긴장해서 실수했네요.',
    aiAdvice: '### 근본 원인 인사이트\n시각적 정보 처리에서의 주의력 분산이 원인입니다.\n\n### 다른 수험생들과의 비교\n그래프 해석 실수는 과학탐구에서 가장 흔한 실수 중 하나입니다. 차분한 확인 과정이 필요합니다.\n\n### 행동 강령\n1. 그래프 문제 시 축부터 확인\n2. 단위와 범위 체크하기\n3. 답 도출 후 그래프에 다시 대입해보기',
    createdAt: Date.now() - 100000,
    likes: 41,
    dislikes: 3,
    isPublic: true,
    rewardClaimed: true
  },
  {
    id: 'mock-10',
    authorId: 'user-10',
    authorName: '사탐고수',
    title: '한국사 연도 헷갈려서 순서 문제 틀림',
    date: '2024-07-08',
    category: 'Mock Exam',
    score: '한국사 3등급',
    tags: ['개념 부족', '과도한 고민(함정)'],
    description: '조선 후기 사건들의 순서를 헷갈렸어요. 정유재란과 정묘호란 순서를 바꿔서 생각했네요.',
    aiAdvice: '### 근본 원인 인사이트\n역사적 사건의 시간적 맥락 이해가 부족합니다.\n\n### 다른 수험생들과의 비교\n한국사에서 연도 암기는 모든 수험생의 약점입니다. 스토리텔링 방식으로 기억하는 것이 효과적입니다.\n\n### 행동 강령\n1. 시대순 연표 만들어 반복 학습\n2. 사건 간 인과관계 파악하기\n3. 키워드 중심 암기법 활용',
    createdAt: Date.now() - 80000,
    likes: 33,
    dislikes: 2,
    isPublic: true,
    rewardClaimed: true
  },
  {
    id: 'mock-11',
    authorId: 'user-11',
    authorName: '영어마스터',
    title: '영어 빈칸추론에서 함정에 빠짐',
    date: '2024-08-22',
    category: 'Mock Exam',
    score: '영어 1등급',
    tags: ['과도한 고민(함정)', '긴장/불안감'],
    description: '빈칸 앞뒤 문장만 보고 답을 골랐는데 전체 맥락을 보니 완전 다른 의미였어요. 함정 선택지에 낚였네요.',
    aiAdvice: '### 근본 원인 인사이트\n부분적 정보에 의존한 성급한 판단이 원인입니다.\n\n### 다른 수험생들과의 비교\n빈칸추론은 1등급 학생들도 자주 틀리는 고난도 문제입니다. 전체 흐름 파악이 핵심입니다.\n\n### 행동 강령\n1. 전체 글의 주제 먼저 파악\n2. 빈칸 전후 3문장씩 분석\n3. 선택지를 빈칸에 대입해서 검증',
    createdAt: Date.now() - 70000,
    likes: 56,
    dislikes: 4,
    isPublic: true,
    rewardClaimed: true
  },
  {
    id: 'mock-12',
    authorId: 'user-12',
    authorName: '수학천재꿈나무',
    title: '확률 문제에서 경우의 수 계산 실수',
    date: '2024-09-18',
    category: 'Mock Exam',
    score: '수학 2등급',
    tags: ['실수(계산/마킹)', '시간 조절 실패'],
    description: '조합과 순열을 헷갈려서 계산했어요. 문제를 다시 읽어보니 순서가 상관없는 문제였는데 순열로 계산했네요.',
    aiAdvice: '### 근본 원인 인사이트\n문제 조건 파악에서의 부주의가 원인입니다.\n\n### 다른 수험생들과의 비교\n확률과 통계는 실수가 가장 많이 나오는 단원입니다. 조건을 명확히 파악하는 것이 중요합니다.\n\n### 행동 강령\n1. 순서의 중요성 여부 먼저 판단\n2. 문제에서 요구하는 것 정확히 파악\n3. 계산 전 어떤 공식을 쓸지 결정',
    createdAt: Date.now() - 60000,
    likes: 45,
    dislikes: 2,
    isPublic: true,
    rewardClaimed: true
  },
  {
    id: 'mock-13',
    authorId: 'user-13',
    authorName: '지구과학탐험가',
    title: '지구과학 천체 관측 문제에서 방향 착각',
    date: '2024-10-01',
    category: 'Mock Exam',
    score: '지구과학 2등급',
    tags: ['개념 부족', '실수(계산/마킹)'],
    description: '별의 일주운동 방향을 반대로 생각했어요. 동쪽에서 서쪽으로 도는 건데 서쪽에서 동쪽으로 돈다고 했네요.',
    aiAdvice: '### 근본 원인 인사이트\n공간 지각 능력과 개념 이해의 연결이 부족합니다.\n\n### 다른 수험생들과의 비교\n천체 관측 문제는 많은 학생들이 어려워하는 영역입니다. 시각적 이해가 중요합니다.\n\n### 행동 강령\n1. 천체 운동을 직접 그려보며 이해\n2. 관측자 시점에서 생각하기\n3. 기본 개념을 반복 학습',
    createdAt: Date.now() - 50000,
    likes: 22,
    dislikes: 1,
    isPublic: true,
    rewardClaimed: true
  },
  {
    id: 'mock-14',
    authorId: 'user-14',
    authorName: '세계사여행자',
    title: '세계사 문화사에서 지역 헷갈림',
    date: '2024-08-30',
    category: 'Mock Exam',
    score: '세계사 3등급',
    tags: ['개념 부족', '과도한 고민(함정)'],
    description: '이슬람 문화와 인도 문화를 헷갈렸어요. 건축 양식이 비슷해서 구분이 안 됐네요.',
    aiAdvice: '### 근본 원인 인사이트\n문화적 특징의 세부적 차이점 파악이 부족합니다.\n\n### 다른 수험생들과의 비교\n세계사 문화사는 암기량이 많아 많은 학생들이 혼동합니다. 체계적 분류가 필요합니다.\n\n### 행동 강령\n1. 지역별 문화 특징 표로 정리\n2. 시각 자료 활용한 학습\n3. 문화 간 차이점 중심 암기',
    createdAt: Date.now() - 40000,
    likes: 18,
    dislikes: 3,
    isPublic: true,
    rewardClaimed: true
  },
  {
    id: 'mock-15',
    authorId: 'user-15',
    authorName: '경제학도',
    title: '경제 그래프에서 수요공급 곡선 착각',
    date: '2024-09-25',
    category: 'Mock Exam',
    score: '경제 2등급',
    tags: ['개념 부족', '실수(계산/마킹)'],
    description: '수요 증가인데 공급 증가로 잘못 봤어요. 그래프에서 화살표 방향을 잘못 해석했네요.',
    aiAdvice: '### 근본 원인 인사이트\n그래프 해석 능력과 경제 개념의 연결이 부족합니다.\n\n### 다른 수험생들과의 비교\n경제 그래프는 많은 학생들이 어려워하는 부분입니다. 기본 개념의 시각적 이해가 중요합니다.\n\n### 행동 강령\n1. 수요공급 기본 개념 재정립\n2. 그래프 변화 요인 체계적 분석\n3. 실생활 예시와 연결하여 이해',
    createdAt: Date.now() - 30000,
    likes: 37,
    dislikes: 2,
    isPublic: true,
    rewardClaimed: true
  },
  {
    id: 'mock-16',
    authorId: 'user-16',
    authorName: '정치외교관',
    title: '정치와법 헌법 조항 암기 실수',
    date: '2024-07-14',
    category: 'Mock Exam',
    score: '정치와법 3등급',
    tags: ['개념 부족', '과도한 고민(함정)'],
    description: '헌법 조항 번호를 헷갈렸어요. 비슷한 내용들이 많아서 구분이 어려워요.',
    aiAdvice: '### 근본 원인 인사이트\n법조문의 체계적 이해보다 단순 암기에 의존했습니다.\n\n### 다른 수험생들과의 비교\n정치와법은 암기 과목으로 인식되지만, 논리적 이해가 더 중요합니다.\n\n### 행동 강령\n1. 헌법 체계와 원리 먼저 이해\n2. 조항별 핵심 키워드 정리\n3. 사례와 연결하여 학습',
    createdAt: Date.now() - 25000,
    likes: 29,
    dislikes: 4,
    isPublic: true,
    rewardClaimed: true
  },
  {
    id: 'mock-17',
    authorId: 'user-17',
    authorName: '사회문화연구자',
    title: '사회문화 통계 해석에서 비율 계산 실수',
    date: '2024-08-05',
    category: 'Mock Exam',
    score: '사회문화 2등급',
    tags: ['실수(계산/마킹)', '시간 조절 실패'],
    description: '백분율 계산에서 소수점을 잘못 처리했어요. 계산기 없이 하다 보니 실수가 났네요.',
    aiAdvice: '### 근본 원인 인사이트\n수치 계산에서의 정확성이 부족합니다.\n\n### 다른 수험생들과의 비교\n사회문화 통계 문제는 계산 실수가 자주 발생하는 영역입니다. 체계적 계산 과정이 필요합니다.\n\n### 행동 강령\n1. 계산 과정을 단계별로 기록\n2. 답의 합리성 검토하기\n3. 반올림 규칙 명확히 적용',
    createdAt: Date.now() - 20000,
    likes: 31,
    dislikes: 1,
    isPublic: true,
    rewardClaimed: true
  },
  {
    id: 'mock-18',
    authorId: 'user-18',
    authorName: '윤리학자',
    title: '생활과윤리 사상가 이론 혼동',
    date: '2024-09-10',
    category: 'Mock Exam',
    score: '생활과윤리 3등급',
    tags: ['개념 부족', '과도한 고민(함정)'],
    description: '칸트와 벤담의 이론을 헷갈렸어요. 의무론과 결과론의 차이를 명확히 구분 못했네요.',
    aiAdvice: '### 근본 원인 인사이트\n철학적 개념의 본질적 차이 이해가 부족합니다.\n\n### 다른 수험생들과의 비교\n윤리 사상가들의 이론 구분은 많은 학생들이 어려워합니다. 핵심 개념 중심 학습이 필요합니다.\n\n### 행동 강령\n1. 사상가별 핵심 주장 정리\n2. 대립되는 이론들 비교 학습\n3. 실제 사례에 적용해보기',
    createdAt: Date.now() - 15000,
    likes: 26,
    dislikes: 2,
    isPublic: true,
    rewardClaimed: true
  },
  {
    id: 'mock-19',
    authorId: 'user-19',
    authorName: '철학도',
    title: '윤리와사상 동양철학 개념 혼동',
    date: '2024-07-28',
    category: 'Mock Exam',
    score: '윤리와사상 3등급',
    tags: ['개념 부족', '과도한 고민(함정)'],
    description: '유교와 도교의 개념을 섞어서 이해했어요. 인(仁)과 도(道)의 차이를 명확히 몰랐네요.',
    aiAdvice: '### 근본 원인 인사이트\n동양철학의 근본 개념들에 대한 이해가 피상적입니다.\n\n### 다른 수험생들과의 비교\n동양철학은 개념이 추상적이어서 많은 학생들이 혼동합니다. 체계적 접근이 필요합니다.\n\n### 행동 강령\n1. 각 사상의 핵심 개념 명확히 정리\n2. 사상가별 주요 저작과 연결\n3. 현대적 의미로 재해석해보기',
    createdAt: Date.now() - 10000,
    likes: 23,
    dislikes: 3,
    isPublic: true,
    rewardClaimed: true
  },
  {
    id: 'mock-20',
    authorId: 'user-20',
    authorName: '미래의의사',
    title: '면접에서 긴장해서 준비한 답변 까먹음',
    date: '2024-10-15',
    category: 'Mock Interview',
    tags: ['긴장/불안감', '무기력/번아웃'],
    description: '의대 면접에서 너무 긴장해서 평소에 달달 외웠던 답변을 완전히 까먹었어요. 머릿속이 하얘졌네요.',
    aiAdvice: '### 근본 원인 인사이트\n과도한 긴장으로 인한 기억 차단 현상이 발생했습니다.\n\n### 다른 수험생들과의 비교\n면접에서의 긴장은 모든 수험생이 겪는 문제입니다. 실전 연습과 마음가짐이 중요합니다.\n\n### 행동 강령\n1. 모의면접을 통한 실전 연습\n2. 긴장 완화 호흡법 익히기\n3. 핵심 키워드 중심 답변 준비',
    createdAt: Date.now() - 5000,
    likes: 78,
    dislikes: 1,
    isPublic: true,
    rewardClaimed: true
  }
];